### ISSUE TITLE
Be careful with adding comments

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#1]
I would like to suggest to refrain having comments in code -- unless for javadoc / API docs or when it is absolutely necessary

If you can, please refrain yourself from adding comments like:
`/*prints out number of asterisks horizontally depending on integerVal(value of integer)*/`
e.g.
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputTriangleExercises.java#L7

--

Typically comments are added to:
1. Give description of what the code is doing. 
2. Give more information to other developers (or future you).

--

**One major problem with having comments: comments lie.**
When the code and the comment contradict each other, which one should you trust?
Is the code incorrect, or is the comment incorrect?
For example:
`/* Process the last item first */`
`items.first().process()`

**Another major problem with having comments: non-simultaneous updates as a consequence of duplication**
If you update the code, frequently you will forget to update the comment around the code. Because there is typically nothing that forces you to ensure the code and comments stay consistent.
For example:
Originally the code looks like this:
`/* Need to get data from input.txt */`
`String data = File.read("input.txt");`

Then requirements change and the code change -- but the comment is not updated
`/* Need to get data from input.txt */`
`String data = File.read("data.csv");`
(In this case, nothing forces the developer to update the comment to be consistent with the code)

-- 

So how would you allow more information about the code to pass to other developers or to your future self?

1. One way is to ensure the code is descriptive, choosing method and variable names carefully and opt for readability
2. Another way is to ensure the tests are descriptive -- and having tests as living documentation of your code. (living documentation because if the code change significantly, you will have to update your tests to reflect that as well.

**Comment by AliciaSJ** [comment]
I have removed the comments from the src files and renamed the tests
