### ISSUE TITLE
Inconsistent spacing / indentation in PrimeFactors

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#10]
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrimeFactors.java#L16

https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrimeFactors.java#L19

**Comment by AliciaSJ** [comment]
Fixed

**Comment by lfendytw** [comment]
Good, thanks
