### ISSUE TITLE
Inconsistent spacing in FizzBuzz

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#11]
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/FizzBuzz.java#L16

You have to be disciplined and rigorous in your code.
Having inconsistent spacing / indentation, or maybe incorrect spelling here and there implies carelessness and apathy.

**Comment by AliciaSJ** [comment]
Fixed

**Comment by lfendytw** [comment]
Good, thanks
