### ISSUE TITLE
Rename back TriangleHelper to TriangleRenderer, move asterisks method out, put the two triangle methods in (isoceles and right angle)

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#12]
https://github.com/AliciaSJ/TW_Intro/blob/24527bf3ade41eba8be74dcdbdb1901bad6632d7/src/main/TriangleRenderer.java

This class does not render any triangle.

Perhaps the isoceles triangle and the right sided triangle should live here

**Comment by AliciaSJ** [comment]
Renamed TriangleRenderer to TriangleHelper

**Comment by lfendytw** [comment]
What I was implying by saying the TriangleRenderer Class name "lie" -- I was suggesting that the methods live in the wrong places.

Naming the class TriangleRenderer is OK.
But the vertical asterisks and asterisks should no longer live here.

The method that should live here is the isoceles triangle and the rightSidedTriangle.

Renaming this TriangleHelper is still incorrect.

**Comment by AliciaSJ** [comment]
I have already moved the two methods out and renamed TriangleHelper back to TriangleRenderer. I misunderstood what you were implying last time. Renaming the class back to TriangleRenderer(while it contains displayIsoscelesTriangle and getRightAngledTriangle) makes sense as it renders triangle. But I have a question, since both of the methods types are different(like you said, the levels of abstractions in methods of a class should be the same) and having different levels of abstractions makes it inconsistent and confusing, do you reckon that I change the method type of displayIsoscelesTriangle to String or getRightAnglesTriangle to void? May I know what is your opinion in this?

**Comment by lfendytw** [comment]
In general I would prefer having a method that returns something
(especially in a collaborator class), rather than a method that returns a
void.
(In this case the TriangleExercise is the calling context and
triangleRenderer is the collaborator)

The reason behind it is twofold.

*Firstly*, by returning a string (instead of void) it will pass the control
back to the calling context (the line of code that invites that function)

E.g.

Int lines = 5;
String triangle = triangleRenderer.getIsocelesTriangle(lines);
System.out.println(triangle);
// In this case the calling context have control over the result of the
getIsocelesTriangle method invocation. So the control is passed back from
triangleRenderer
System.out.println("done");


For void method:
Int lines = 5;
triangleRenderer.displayIsocelesTriangle(lines);
System.out.println("done");

In contrast, void method does not pass the control back.
Even if after invoking "displayIsocelesTriangle" the next line is executed,
triangleRenderer doesn't actually pass the control back, because the
calling context *can't make further decisions* after making the method
call. The decision to print out to console was made inside
triangleRenderer, so triangleExercise (the calling context) has no control.

Also, printing and creating the triangle are *two different
responsibilities.* So the void method breaks SRP.

----------------------------

*Secondly, *method that returns a string satisfies the "principle of least
surprise". This is due to limiting side effects.
System.out.println inside the triangleRenderer void method is a *side
effect.  *Returning a string does not have a side effect.

Read the following code:

System.out.prinln("start");
triangleRenderer.displayIsocelesTriangle(5);
System.out.println("done");

in this case, it is *not* obvious that you are printing triangle unless you
already know what "displayIsocelesTriangle" does -- but that means you have
to go in and read the code first.

vs

System.out.println("start");
System.out.println(triangleRenderer.getIsocelesTriangle(5));
System.out.println("done");

in this case, it is obvious that you are trying to print -start-,
-triangle-, -done-

---------------------

Let me know of you have more questions.

**Comment by lfendytw** [comment]
In general I would prefer having a method that returns something (especially in a collaborator class), rather than a method that returns a void.
(In this case the TriangleExercise is the calling context and triangleRenderer is the collaborator)

The reason behind it is twofold.

**Firstly**, by returning a string (instead of void) it will pass the control back to the calling context (the line of code that invites that function)

E.g.

Int lines = 5;
String triangle = triangleRenderer.getIsocelesTriangle(lines);
System.out.println(triangle);
// In this case the calling context have control over the result of the getIsocelesTriangle method invocation. So the control is passed back from triangleRenderer
System.out.println("done");


For void method:
Int lines = 5;
triangleRenderer.displayIsocelesTriangle(lines);
System.out.println("done");

In contrast, void method does not pass the control back.
Even if after invoking "displayIsocelesTriangle" the next line is executed, triangleRenderer doesn't actually pass the control back, because the calling context can't make further decisions after making the method call. The decision to print out to console was made inside triangleRenderer, so triangleExercise (the calling context) has no control.

Also, printing and creating the triangle are **two different responsibilities**. So the void method breaks SRP.

----------------------------

**Secondly**, method that returns a string satisfies the "principle of least surprise". This is due to limiting side effects.
System.out.println inside the triangleRenderer void method is a side effect.  Returning a string does not have a side effect.

Read the following code:

System.out.prinln("start");
triangleRenderer.displayIsocelesTriangle(5);
System.out.println("done");

in this case, it is **not** obvious that you are printing triangle unless you already know what "displayIsocelesTriangle" does -- but that means you have to go in and read the code first.

vs

System.out.println("start");
System.out.println(triangleRenderer.getIsocelesTriangle(5));
System.out.println("done");

in this case, it is obvious that you are trying to print -start-, -triangle-, -done-

---------------------

Let me know if you have more questions.

**Comment by AliciaSJ** [comment]
Thank you for the detailed explanation. That was really helpful! I have changed the return type from void to String for displayIsoscelesTriangle. 

So is what you're saying in the first part something similar to the MVC(Model-View-Controller) concept? 

And for the second part, I have googled it and it came out to Principle of Least Astonishment, I am guessing that it is the same thing as what you were saying, which is Principle of Least Surprise. I have read another explanation that is related to the real-world and it really helped me to understand more. The explanation was "Think of a web page that has pop up window that shows a windows style error with an 'ok' button on it. People click the 'ok' button thinking it is for the operating system and instead go to another web page".

**Comment by lfendytw** [comment]
The principle of least surprise applies equally to programming. When you
are writing your code you need to keep in your mind the future consumer of
your code. This could be the future you (you in 6 months time), or another
developer.

This means making things as explicit as possible. Make it very very clear
what your intentions are. If your code does more things than one, that's
surprising. When your code has side effects (e.g. unexpected console out),
that's surprising. When your method name / class name is misleading (e.g.
triangleRenderer has no methods that renders triangle), that's surprising.

If you consider your code as your "product' and the future developer as
your "user/consumer' -- then the principle of least surprise or least
astonishment applies equally.




Liauw Fendy   |   +61 3 9691 6500   |   ThoughtWorks Australia

**Comment by lfendytw** [comment]
Yes, to a certain extent - my first part of the explanation relate to MVC.

Model contains business logic and View contains presentation logic and
thats how SRP is applied.

Liauw Fendy   |   +61 3 9691 6500   |   ThoughtWorks Australia

**Comment by AliciaSJ** [comment]
The way you've explained things about the principle of least surprise is really straightforward and easy to be understood. 

What else do you think makes a code good in terms of quality? Do you have any other tips other than what you've already told me(naming conventions ,SRP ,comments)? I know briefly what makes a good quality code, which is making sure a function only does one thing(high cohesion) and making sure that they're not dependent on others(low coupling).

**Comment by lfendytw** [comment]
Another aspect of principle of least surprise is idiomatic programming.

This means understanding the conventions behind a specific framework or
language and follow them, instead if trying to be "smart".

Example here is keeping method names as verbs and class names as nouns.
This is idiomatic to object oriented programming / language.

In Java, uppercase names are typically reserved for class names. This is
also idiomatic java.

When you depart from these, it is surprising and potentially confusing to
future developers.

-------------------

The underlying principle would be readability / maintainability.

You want to reduce the mental workload of future developers to understand
your code. You want to write LESS code and you want to write them as simple
and clean as possible.

This means using abstraction correctly. Keep the same level if abstraction
in a class. Short methods, short classes, having a class contain only one
Responsibility (or one reason to change) and have your tests describe /
document your intent.




Liauw Fendy   |   +61 3 9691 6500   |   ThoughtWorks Australia

**Comment by AliciaSJ** [comment]
I will use abstraction correctly from now on as, if the abstraction levels are consistent in a class, it will be easier to know where to get the information from next time. Speaking of that, naming(including knowing the difference between uppercase and lowercase names) is also very important as it provides future developers information on what does a certain class/method do, what are the test methods actually testing for, what is the variable actually storing and so on. 

I will keep those in mind whenever I write code next time. Thanks!

**Comment by lfendytw** [comment]
The method names are asymmetrical. One is get, the other is display.
And the display method is misleading

**Comment by AliciaSJ** [comment]
I have changed displayIsoscelesTriangle to getIsoscelesTriangle. Why do you think the display method misleading? Is it because of the method name as it is not displaying anything?

**Comment by lfendytw** [comment]
Yes it is not displaying anything

Liauw Fendy   |   +61 3 9691 6500   |   ThoughtWorks Australia
