### ISSUE TITLE
Code duplication in FizzBuzz

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#13]
https://github.com/AliciaSJ/TW_Intro/blob/24527bf3ade41eba8be74dcdbdb1901bad6632d7/src/main/FizzBuzz.java

FizzBuzzIndividual contains 80-90% of the business logic of fizzBuzz.
This should not be duplicated.

**Comment by AliciaSJ** [comment]
Moved the duplicated code to a new class
