### ISSUE TITLE
Code duplication in DiamondRenderer

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#14]
https://github.com/AliciaSJ/TW_Intro/blob/24527bf3ade41eba8be74dcdbdb1901bad6632d7/src/main/DiamondRenderer.java

There is duplicated code between the isocelesTriangle and diamond.

**Comment by AliciaSJ** [comment]
Added diamondHelper in diamondRenderer to prevent duplication of code

**Comment by lfendytw** [comment]
Unfortunately removing the duplication this way makes the code very difficult to read
