### ISSUE TITLE
Inconsistent case in variable names in DiamondRenderer

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#15]
https://github.com/AliciaSJ/TW_Intro/blob/24527bf3ade41eba8be74dcdbdb1901bad6632d7/src/main/DiamondRenderer.java

Why does CtrSpace start with a capital letter?
In Java, you typically reserve words that starts with an uppercase for Class names

**Comment by AliciaSJ** [comment]
Renamed the variables to asteriskCounter and spaceCounter
