### ISSUE TITLE
Avoid abbreviating variable names unless absolutely necessary

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#16]
https://github.com/AliciaSJ/TW_Intro/blob/24527bf3ade41eba8be74dcdbdb1901bad6632d7/src/main/DiamondRenderer.java

CtrSpace can mean counterSpace, cultureSpace, craterSpace.

**Comment by AliciaSJ** [comment]
renamed the variables to asteriskCounter and spaceCounter
