### ISSUE TITLE
Test method names should be descriptive and show intent

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#17]
https://github.com/AliciaSJ/TW_Intro/blob/24527bf3ade41eba8be74dcdbdb1901bad6632d7/src/main/DiamondRenderer.java

Instead of testDrawAHorizontalLine(), perhaps name them 
drawAHorizontalLineShouldPrintANumberOfAsterisksInALineAccordingToInput()

**Comment by AliciaSJ** [comment]
Renamed test method names in all test files
