### ISSUE TITLE
getAstericks?

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#18]
https://github.com/AliciaSJ/TW_Intro/blob/3564405a99ee5f8e8274ad83c362664ec74ab32a/src/main/TriangleHelper.java#L7

Firstly, Asteri**s**ks is mispelled.

Secondly, Since you have getVerticalAsterisks, it might make sense to differentiate it by having
getHorizontalAsterisks

**Comment by AliciaSJ** [comment]
Thank you for the feedback. It totally makes sense to have getHorizontalAsterisks as I have a getVerticalAsterisks. It maintains consistency in naming conventions. I will be more careful in my naming conventions next time.
