### ISSUE TITLE
Passing in "*" is unnecessary

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#19]
https://github.com/AliciaSJ/TW_Intro/blob/3564405a99ee5f8e8274ad83c362664ec74ab32a/src/main/TriangleHelper.java#L7

https://github.com/AliciaSJ/TW_Intro/blob/3564405a99ee5f8e8274ad83c362664ec74ab32a/src/main/TriangleHelper.java#L19

https://github.com/AliciaSJ/TW_Intro/blob/3564405a99ee5f8e8274ad83c362664ec74ab32a/src/main/TriangleHelper.java#L33

Because the method already indicate the it is getting Asterisks, there is no need to pass on asterisks.

Consider the case where the method is invoked differently:

AsterisksRenderer.getVerticalAsterisks("?", 5);
this invocation now lies because it's no longer getting a verticalAsterisks of length 5,
instead it is getting question marks (what is being passed through) of length 5.

**Comment by AliciaSJ** [comment]
Instead of passing in both strings and integers as parameters to the all of the methods in AsterisksRenderer, I have changed the parameters to just the integer, which is the length of the asterisks. 
What I have learnt from this is that, be skeptical about your own code. For example in this case, what is going to make the code "lie".

**Comment by lfendytw** [comment]
Another reason:
prevent duplication.

getVerticalAsterisks("*", 5)

the asterisks is duplicated in the method name and in the parameter.
This means:

1. It could differ and therefore no longer be consistent (i.e. "lie")
2. It is resistant to change
-- if requirements change in the future and you need to print hyphens instead of asterisks
-- you will need to change the method into:
getVerticalHyphens("-",5);
// which is a change both in the method name and in the parameter

You should make a choice on either keeping the method name, or keeping the parameter.
so choose between:

getVerticalAsterisks(5)
or
getVerticalCharacters("*", 5)

**Comment by AliciaSJ** [comment]
Thanks Fendy, I will use that as a guideline when it comes to writing codes next time. Like that you said, it is not wise to have getVerticalAsterisks("^",10) as "^" isn't an asterisk. It makes more sense to just write it as getVerticalAsterisks(10). Or like you've mentioned, write getVerticalCharacters("^",10).
