### ISSUE TITLE
Introduce AsterisksRenderer

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#20]
This seems to be the right place to contain
"getVerticalAsterisks" and "getHorizontalAsterisks"

**Comment by AliciaSJ** [comment]
I have made a new class called AsterisksRenderer and I have moved methods getVerticalAsterisks and getHorizontalAsterisks to AsterisksRenderer. Like I have mentioned in the previous comments about TriangleRenderer, it makes sense to have AsterisksRenderer, as it makes it clearer and more organised for not only me, but also the future developers to read the code and find out what the code in each class does according to the name.
