### ISSUE TITLE
FizzBuzz method should be lower case and ideally a verb

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#23]
https://github.com/AliciaSJ/TW_Intro/blob/3564405a99ee5f8e8274ad83c362664ec74ab32a/src/main/FizzBuzz.java#L9

You typically invoke a method (i.e. you "do" something). So it makes sense to keep method name a verb.

Also, I have mentioned that it is good practice to keep variable and method names start with a lower case. We typically reserve UpperCase for Class names.

**Comment by AliciaSJ** [comment]
I have renamed the method names in FizzBuzz to displayFizzBuzzList and displayIndividualFizzBuzz. I will keep those rules in mind as a guideline in naming my methods next time.
