### ISSUE TITLE
Use the same style of assert as the one you use in diamondWithName

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#24]
https://github.com/AliciaSJ/TW_Intro/blob/3564405a99ee5f8e8274ad83c362664ec74ab32a/src/test/DiamondExercisesTest.java

Write the asserts to make it easier to read:

        assertEquals("  *" + newLine +
                " ***" + newLine +
                name + newLine +
                " ***" + newLine +
                "  *"+newLine, outContent.toString());

or.. even better:

        assertEquals(
                "  *"   + newLine +
                " ***"  + newLine +
                name    + newLine +
                " ***"  + newLine +
                "  *"   + newLine, outContent.toString());

**Comment by AliciaSJ** [comment]
I have cleaned up the codes in the test files to increase the readability. Do check them out to see what you think of them and if I need to make anymore changes.

**Comment by lfendytw** [comment]
I still find it quite difficult to read unfortunately...

Was hoping to see:

    diamondShouldReturnACentredDiamondAccordingToInput()
    assertEquals(
            "  *"   + newLine +
            " ***"  + newLine +
            "*****" + newLine +
            " ***"  + newLine +
            "  *"   + newLine, outContent.toString());


and

    isoscelesTriangleShouldReturnACentredTriangleAccordingToInput()
    assertEquals(
            "  *"   + newLine +
            " ***"  + newLine +
            "*****" + newLine, outContent.toString());

**Comment by AliciaSJ** [comment]
Thank you for the feedback. I have cleaned up the code. Let me know if it is readable and up to expectations.
