### ISSUE TITLE
FizzBuzzTest is correct, but not strictly complete

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#25]
I can write this (incorrect) code and it will still pass your tests:

    public static void getFizzBuzz(int i){

        if((i == 15) || (i == 60)){
            System.out.println("FizzBuzz");

        }
        else if(i == 3){
            System.out.println("Fizz");

        }
        else if(i == 5){
            System.out.println("Buzz");

        }
        else{
            System.out.println(i);
        }

    }

**Comment by AliciaSJ** [comment]
I have added more tests in FizzBuzzTest. Let me know what do you think of them. I am still pretty new to TDD so if there is anything you would like to share about TDD, I would be very excited to hear about it. Thanks!

**Comment by lfendytw** [comment]
Hi Alicia,

Although correct, (and in this case complete). The tests do not communicate to the other future developer what you intend the code to do. Also, having more tests are not necessarily better.

Some examples of test name and how it could be written:

public void getIndividualFizzBuzzShouldReturnFizzForMultiplesOfThreeOnly() {
  List<Integer> multiplesOfThree = new ArrayList<Integer>(Arrays.asList(3,6,9,12));
  for (Integer multipleOfThree : multiplesOfThree) {
        assertEquals("Fizz", FizzBuzz.getIndividualFizzBuzz(multipleOfThree));
    }
}

This will then communicate the intent of the test to future developers.

Having a test that is very specific (like getIndividualFizzBuzzOf60ShouldReturnFizzBizz) does not give this visibility -- i.e. the future developer would still have to guess what the code does / intends to do.

--------------------------------------

Another reason:

Typically we write unit test in such a way that **it can fail individually**.
By writing:
getIndividualFizzBuzzOf60ShouldReturnFizzBuzz()
and
getIndividualFizzBuzzOf120ShouldReturnFizzBuzz()

--> These tests cannot fail independently of each other.

**Comment by lfendytw** [comment]
also, I realise that the location of the test is not quite correct.

To test the business logic (translating between number and fizzbuzz) -- this should be in the FizzBuzzRendererTest

**Comment by AliciaSJ** [comment]
Dear Fendy, 

I have a doubt and I need some clarification from you. What I understand from what you're trying to explain to me is that, there is some redundancy in my test methods and I should eliminate them. 

My question is, since it's a norm for us to write a unit test in a way that can fail individually, do we just test for the basic cases, in this case, returning an integer if it is not a multiple of three or five(or both) and also testing for Fizz, Buzz and FizzBuzz? 

For example, my test methods would be 
- displayIndividualFizzBuzzOfOneShouldReturnOne()
- displayIndividualFizzBuzzOfThreeShouldReturnFizz()
- displayIndividualFizzBuzzOfFiveShouldReturnBuzz()
- displayIndividualFizzBuzzOfFifteenShouldReturnFizzBuzz() 

I should not write test(like the test methods below) if I have the above test methods as they're redundant. 
- displayIndividualFizzBuzzOfNineShouldReturnFizz()
- displayIndividualFizzBuzzOf33ShouldReturnFizz()
- displayIndividualFizzBuzzOfSixtyShouldReturnFizzBuzz()
- displayIndividualFizzBuzzOf125ShouldReturnBuzz()

Let me know if what I understood is correct.

**Comment by lfendytw** [comment]
Hi Alicia,

For example, my test methods would be

   - displayIndividualFizzBuzzOfOneShouldReturnOne()
   - displayIndividualFizzBuzzOfThreeShouldReturnFizz()
   - displayIndividualFizzBuzzOfFiveShouldReturnBuzz()
   - displayIndividualFizzBuzzOfFifteenShouldReturnFizzBuzz()

*Generally this is sufficient, but the thing is the name of the test (and
likely the assertion) does not indicate what you intend the code to do. A
future developer won't know what 6 will return for example -- just by
reading your tests. I suggest to write the test in terms of business logic
or business value. The spec says, multiplesOfThreeShouldReturnFizz and
multiplesOfFiveShouldReturnBuzz and
multiplesOfThreeAndFiveShouldReturnFizzBuzz and
numbersNotMultiplesOfThreeNorFiveShouldRemain.*

*So, in my opinion, the test should be written that way. That might mean
multiple assertions in the test.*

*For example [3,6,9,12].each(assert......)*



I should not write test(like the test methods below) if I have the above
test methods as they're redundant.

   - displayIndividualFizzBuzzOfNineShouldReturnFizz()
   - displayIndividualFizzBuzzOf33ShouldReturnFizz()
   - displayIndividualFizzBuzzOfSixtyShouldReturnFizzBuzz()
   - displayIndividualFizzBuzzOf125ShouldReturnBuzz()

*Yes, writing a test like this will mean the test wont fail individually.
Or it is difficult to make the test fail individually -- so typically we
want to avoid these.*




Liauw Fendy
Market Technical Principal for Melbourne
Email lfendy@thoughtworks.com
Telephone +61 3 9691 6500 <+61+3+9691+6500>
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=liauw-fendy-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

**Comment by AliciaSJ** [comment]
Could you explain more about having multiple assertions in a test as I thought having multiple assertions in a test was a bad practice. I have updated the FizzBuzzRendererTest, let me know what you think!

**Comment by lfendytw** [comment]
When you assert 3,6,9,12 returns fizz -- this is multiple assertions/scenarios for the same business logic. Which in my opinion is OK. This is because it is still testing the same business logic and the test as a whole describes the intent (multiplesOfThree returns Fizz).
