### ISSUE TITLE
Be clean and rigorous about your code.

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#3]
Keep your code clean and maintain standard spacing convention in your code.

e.g.
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputTriangleExercises.java#L24

`L23 asterisks += asterisk;`
`L24 asterisks+=System.lineSeparator();`

Why is there no space in += in line 24?

Having inconsistent spacing / indentation, or maybe incorrect spelling here and there implies carelessness and apathy.

**Comment by AliciaSJ** [comment]
Cleaned up codes on in both src and test files
