### ISSUE TITLE
PrintOutputTriangleExercise class name makes no sense

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#4]
The file name and the class name: "PrintOutputTriangleExercise" does not describe what the class is doing.

https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputTriangleExercises.java#L5

**First of all,** 
"Print" implies that the class will print something -- either to a hardware device (like a physical printer) or to the standard out or console.
This class does neither. So the class name is lying.

A more apt description is something that explains what it does:
Maybe Draw, Paint, or Render

**Secondly,**
Using a verb as a class name is typically not recommended. This is because Java is an object oriented language and the Class will eventually represent an object (conceptually). It will not represent an "in-progress action" like a verb.
So it **does not** make sense to call a class something like "PrintTriangle". It makes more sense to call it "TrianglePrinter".

When you eventually use the class (if it is static).. It will then read:
`TriangleRenderer.renderTriangle(5)`

Consider writing a sentence about someone eating food.
You would **not** write "Eat food is eating food", instead it makes more sense to write "Food eater is eating food" or "Mike is eating food"
Similarly in code, we don't write 
`EatFood.eatFood("candy");`
instead we should write
`FoodConsumer.eatFood("candy");`
or
`Mike.eatFood("candy");`
 
**Thirdly,**
"Exercise" is not a concept that is important to this class.
So I would be quite hesitant on renaming "PrintOutputTriangleExercise" into "TriangleExerciseRenderer". Because nothing in the class indicates that it is exercising something and the concept of it being a "ThoughtWorks Exercise" means nothing.

To give an extreme example. It makes no sense to write the class as:
`public class AliciaSolutionTriangleRendererForThoughtworksExerciseWrittenYesterday()`
The reason, is obviously, because "Alicia", "Solution", "ThoughtworksExercise", "WrittenYesterday" are all concepts that has nothing to do with the class.

This applies similarly to the concept "Output". Naming a class as "TriangleRendererOutput" will be superfluous and unecessary.

**Comment by AliciaSJ** [comment]
Renamed file from PrintOutputTriangleExercise to TriangleRenderer

**Comment by lfendytw** [comment]
triangleRenderer className lies.
It does nothing to do with rendering triangles.
