### ISSUE TITLE
printAsterisks and printVerticalAsterisks lie

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#5]
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputTriangleExercises.java#L8
and
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputTriangleExercises.java#L19

See https://github.com/AliciaSJ/TW_Intro/issues/4

printAsterisks does not "print". So it is lying.

**Comment by AliciaSJ** [comment]
renamed both methods
