### ISSUE TITLE
incorrect (asymmetric) level of abstraction in printRightAngledTriangle

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#6]
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputTriangleExercises.java#L31

Every other method in this class returns a string, but the "printRightAngledTriangle"  is instead a void function that immediately prints to standardOut. 

This is mixing different level of abstraction in the same class -- which makes it inconsistent and potentially confusing.

Even if the method name is correct -- because it is actually printing out -- It is still confusing for future developers because it doesn't make sense where some of the methods return string and some of the other methods prints immediately.

-----------

Also, by printing out the result immediately to standard out in this method, you are mixing business logic with presentation logic. This breaks SRP (Single Responsibility Principle).
The business logic in this case is turning an integer into a bunch of strings.
The presentation logic in this case is putting the string into standard out.
By mixing business logic and presentation logic, you will now need to remember all the places where presentation logic lives in order to make a change in your code.

For example.
When a new requirement asks you to write to a file, instead of printing to standardout console, then you will need to hunt down all the places where you have System.out.println and change it to FileStream.Write().

**Comment by AliciaSJ** [comment]
I have removed the method type void from PrintOutputTriangleExercises.java

**Comment by lfendytw** [comment]
The triangleRenderer now no longer have any print method. Which is good. But the TriangleExercise now contain business logic which might be better at the triangleRenderer. What about moving the right angle triangle logic into triangleRenderer and let it return a string. Then print them out at triangleExercise?

**Comment by AliciaSJ** [comment]
I have moved the business logic from triangleExercise to TriangleRenderer
