### ISSUE TITLE
PrintOutputDiamondExercises class name makes no sense

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#7]
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputDiamondExercises.java#L5

see https://github.com/AliciaSJ/TW_Intro/issues/4

**Comment by AliciaSJ** [comment]
Renamed PrintOutputDiamondExercise to DiamondRenderer

**Comment by lfendytw** [comment]
DiamondRenderer breaks SRP because it creates string and print them at the same time. A Renderer should not immediately display. And it's usually good practice to keep system.out.println as far away in the perimeters of your application as possible.

Maybe return a string from the DiamondRenderer and print them out in diamondExercises
