### ISSUE TITLE
method name getIsocelesTriangle and getDiamond and getDiamondWithName lie

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#8]
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputDiamondExercises.java#L7

https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputDiamondExercises.java#L25

https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputDiamondExercises.java##51

See https://github.com/AliciaSJ/TW_Intro/issues/5

**Comment by AliciaSJ** [comment]
Files have been renamed

**Comment by lfendytw** [comment]
Yes that is correct, the files have been renamed. But I'm guessing what you really meant here is that the method names have been renamed to better describe its functions.
