### ISSUE TITLE
DiamondRenderer DisplayIsocelesTriangle and displayDiamond and displayDiamondWithName breaks SRP (Single Responsibility Principle)

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#9]
https://github.com/AliciaSJ/TW_Intro/blob/5e028fbf4e815732e69bc6d6272235dce36eccc2/src/main/PrintOutputDiamondExercises.java#L12

See the second part of https://github.com/AliciaSJ/TW_Intro/issues/6

**Comment by lfendytw** [comment]
This has not been fixed?

DiamondRenderer breaks SRP because it creates string and print them at the same time. A Renderer should not immediately display. And it's usually good practice to keep system.out.println as far away in the perimeters of your application as possible.

Maybe return a string from the DiamondRenderer and print them out in diamondExercises

**Comment by lfendytw** [comment]
I was suggesting to return a string from DiamondRenderer instead of extracting System.out.println to its own class (Printer).

What was your reasoning behind choosing to use the Printer class, instead of returning a string to the DiamondExercises class?

**Comment by lfendytw** [comment]
By the way, moving System.out.println to its own class and still using the the Printer class within the DiamondRenderer **still** breaks SRP

**Comment by AliciaSJ** [comment]
I have changed the return types of the methods in DiamondRenderer to type String. This is to prevent the mixing of business and presentation logic and also to adhere to the rules of SRP. I have deleted class Printer as it is no longer used. 

My reasoning for creating a Printer class was to maintain consistency so I would have a class that contains all of the System.out.println(). It makes things more maintainable and organised. 

Let me know what do you think of my reasoning. Do you think it is appropriate?

**Comment by lfendytw** [comment]
Having a Printer class is fine, although I would suggest calling it a
ConsoleWriter instead.

The issue is that the DiamondRenderer uses the Printer class. And it's not
the responsibility of the DiamondRenderer to print.

In other words, there is virtually no difference between a line that says
"system.out.println" and a line thay says "printer.print". In both cases,
the calling context is the DiamondRenderer. And in both cases, the
DiamondRenderer is taking the responsibility of printing things out to
console.

This is still mixing business logic and presentation logic.

So if you use either a Printer or a ConsoleWriter, the class should still
live outside the DiamondRenderer, maybe in the DiamondExercise class.




Liauw Fendy   |   +61 3 9691 6500   |   ThoughtWorks Australia

**Comment by AliciaSJ** [comment]
Yes, I get what you mean. I would like to explain again on what you're trying to explain just in case I get the wrong idea. As what I did previously was adding a new class specifically for printing/writing to the console. But the way I have used the Printer/ConsoleWriter class is not a good practice as it still mixing both business and presentation logic since I just write Printer.print instead of System.out.print(). I was printing things out and processing the business at the same time, which is not a good practice. It is better to separate classes responsible for business and presentation logic.

Why do you suggest calling it a ConsoleWriter instead of a Printer class? Is it because the name is more specific and tells more to the developers and it writes to the console? Why not ConsolePrinter instead?

**Comment by lfendytw** [comment]
Particularly is the location of which it is invoked.
Extracting the system.out.println to a different class is ok, but because
the calling context is the same, that means the responsibility of the
calling context didn't change.

Previously diamondRenderer is responsible for printing.
After the extraction to Printer class, DiamondRenderer is still responsible
for printing, because it calls the printer class.

ConsolePrinter and ConsoleWriter make little difference.

I have a preference towards writer just because that's how i conceptually
imagine data being passed through. By writing to standard out or to console
interface. Printing implies specifically to displaying. Writing implies
passing data through

Having said that, ConsolePrinter is equally good.



Liauw Fendy   |   +61 3 9691 6500   |   ThoughtWorks Australia

**Comment by AliciaSJ** [comment]
I agree with all of the above and I've also understood what you're trying to tell me about the printer class. It still breaks SRP if system.out.println() is extracted out and being replaced my printer.print(). It is still mixing both business and presentation logic together. 

Speaking of that, has this issue been fixed? Or are there any other adjustments you would like me to make?
